
spring:
  application:
    name: rpc-producer
server:
  port: 8003
swagger:
  enable: true
netty:
  server:
    port: 11211
logging:
  level: warn

wlb:
  rpc:
    enable: true
    client:
      service-name: producer


